# Generated by Django 5.1.7 on 2025-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_flashpromo_promotions__start_t_affc3e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashpromo',
            name='max_distance_km',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
    ]
